---
notifications:
  email:
    on_success: never
    on_failure: change

sudo: true

language: python
python:
  - '2.7'
  - '3.6'

install:
  - sudo apt-get install libxcb-render0-dev
  - pip install tox-travis coveralls
  - python setup.py install

script:
  - tox

after_script:
  - coveralls
