#!/usr/bin/env python
"""
This file provides a script to compare using XCB and Xlib to determine the
window underneath the pointer
"""
# pylint: disable=misplaced-comparison-constant

from sys import exit as sys_exit

from wotw_x11_comparison.pointer_window import PointerWindowComparison


def cli():
    """Bootstraps the comparison"""
    runner = PointerWindowComparison()
    runner.run_many_trials(10000)

if '__main__' == __name__:
    cli()
    sys_exit(0)
